version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html-aliases/utcapp2
permissions:
  - object: /var/www/html-aliases/utcapp2
    pattern: "**"
    owner: utcapp2
    group: www
    mode: 444
    type:
      - file
  - object: /var/www/html-aliases/utcapp2
    pattern: "**"
    owner: utcapp2
    group: www
    mode: 555
    type:
      - directory